// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: dns_server.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HostManagerClient is the client API for HostManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostManagerClient interface {
	AddHosts(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Result, error)
	DelHosts(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Result, error)
	GetHosts(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Result, error)
}

type hostManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewHostManagerClient(cc grpc.ClientConnInterface) HostManagerClient {
	return &hostManagerClient{cc}
}

func (c *hostManagerClient) AddHosts(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/server.HostManager/AddHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostManagerClient) DelHosts(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/server.HostManager/DelHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostManagerClient) GetHosts(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/server.HostManager/GetHosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostManagerServer is the server API for HostManager service.
// All implementations must embed UnimplementedHostManagerServer
// for forward compatibility
type HostManagerServer interface {
	AddHosts(context.Context, *Host) (*Result, error)
	DelHosts(context.Context, *Host) (*Result, error)
	GetHosts(context.Context, *Host) (*Result, error)
	mustEmbedUnimplementedHostManagerServer()
}

// UnimplementedHostManagerServer must be embedded to have forward compatible implementations.
type UnimplementedHostManagerServer struct {
}

func (UnimplementedHostManagerServer) AddHosts(context.Context, *Host) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHosts not implemented")
}
func (UnimplementedHostManagerServer) DelHosts(context.Context, *Host) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelHosts not implemented")
}
func (UnimplementedHostManagerServer) GetHosts(context.Context, *Host) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHosts not implemented")
}
func (UnimplementedHostManagerServer) mustEmbedUnimplementedHostManagerServer() {}

// UnsafeHostManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostManagerServer will
// result in compilation errors.
type UnsafeHostManagerServer interface {
	mustEmbedUnimplementedHostManagerServer()
}

func RegisterHostManagerServer(s grpc.ServiceRegistrar, srv HostManagerServer) {
	s.RegisterService(&HostManager_ServiceDesc, srv)
}

func _HostManager_AddHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostManagerServer).AddHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.HostManager/AddHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostManagerServer).AddHosts(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostManager_DelHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostManagerServer).DelHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.HostManager/DelHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostManagerServer).DelHosts(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostManager_GetHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostManagerServer).GetHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.HostManager/GetHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostManagerServer).GetHosts(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

// HostManager_ServiceDesc is the grpc.ServiceDesc for HostManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.HostManager",
	HandlerType: (*HostManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddHosts",
			Handler:    _HostManager_AddHosts_Handler,
		},
		{
			MethodName: "DelHosts",
			Handler:    _HostManager_DelHosts_Handler,
		},
		{
			MethodName: "GetHosts",
			Handler:    _HostManager_GetHosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dns_server.proto",
}
